{.$define debug_fps} // Show rendering times in ms, in a red label in the corner

{$define use_cache} // Use FAdapterCache, ie caching of colored lines

{.$define debug_findwrapindex}

{$define fix_horzscroll} //workaround for gtk2 widgetset unstable: it freezes app
                         //when horz-scroll hides/shows/hides/...
                         //ok also for win32

{.$define debug_scroll}
