{
Copyright (C) Alexey Torgashin, uvviewsoft.com
License: MPL 2.0 or LGPL
}
unit ATSynEdit_Export_HTML;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, Graphics, StrUtils,
  ATSynEdit,
  ATSynEdit_LineParts,
  ATStringProc_HtmlColor;

procedure DoEditorExportToHTML(Ed: TATSynEdit;
  const AFilename, APageTitle, AFontName: string;
  AFontSize: integer; AWithNumbers: boolean;
  AColorBg, AColorNumbers: TColor);

implementation


procedure DoCssStyle(AColorFont, AColorBg, AColorFontDef, AColorBgDef: TColor;
  out StyleName, StyleText: string);
var
  NameF, TextF, NameBg, TextBg: string;
begin
  if AColorFont<>AColorFontDef then
  begin
    NameF:= TATHtmlColorParserA.ColorToHtmlString(AColorFont);
    TextF:= 'color: '+NameF+'; ';
    Delete(NameF, 1, 1);
  end
  else
  begin
    NameF:= '';
    TextF:= '';
  end;

  if AColorBg<>AColorBgDef then
  begin
    NameBg:= TATHtmlColorParserA.ColorToHtmlString(AColorBg);
    TextBg:= 'background: '+NameBg+'; ';
    Delete(NameBg, 1, 1);
  end
  else
  begin
    NameBg:= '';
    TextBg:= '';
  end;

  StyleName:= '_'+NameF;
  if NameBg<>'' then
    StyleName+= '_'+NameBg;
  StyleText:= '    .'+StyleName+' {'+TextF+TextBg+'}';
end;


function _IsSpaces(const S: string): boolean;
var
  i: integer;
begin
  for i:= 1 to Length(S) do
    if S[i]<>' ' then exit(false);
  Result:= true;
end;


procedure _AddPreToStrings(L: TStringList);
begin
  if L.Count=0 then exit;
  L[0]:= '<pre><code>'+L[0];
  L[L.Count-1]:= L[L.Count-1]+'</code></pre>';
end;

procedure EscapeSpecChars(var S: string); inline;
begin
  S:= StringReplace(S, '&', '&amp;', [rfReplaceAll]);
  S:= StringReplace(S, '<', '&lt;', [rfReplaceAll]);
  S:= StringReplace(S, '>', '&gt;', [rfReplaceAll]);
end;

procedure DoEditorExportToHTML(Ed: TATSynEdit; const AFilename, APageTitle,
  AFontName: string; AFontSize: integer; AWithNumbers: boolean; AColorBg,
  AColorNumbers: TColor);
var
  L, LStyles, LCode, LNums: TStringList;
  Parts: TATLineParts;
  PPart: ^TATLinePart;
  NColorFont: TColor;
  NColorAfter: TColor;
  NeedStyleFont, NeedStyleBg, NeedStyle: boolean;
  S, StrText: string;
  StyleName, StyleText: string;
  i, j: integer;
begin
  if Ed.Strings.Count=0 then exit;

  NColorFont:= clBlack;
  FillChar(Parts, Sizeof(Parts), 0);

  if FileExists(AFilename) then
    DeleteFile(AFilename);

  L:= TStringList.Create;
  LStyles:= TStringList.Create;
  LCode:= TStringList.Create;
  LNums:= TStringList.Create;

  try
    for i:= 0 to Ed.Strings.Count-1 do
      LNums.Add(IntToStr(i+1)+'&nbsp;');
    _AddPreToStrings(LNums);

    for i:= 0 to Ed.Strings.Count-1 do
    begin
      S:= '';
      if not Ed.DoCalcLineHiliteEx(i, Parts, AColorBG, NColorAfter) then break;
      for j:= 0 to High(Parts) do
      begin
        PPart:= @Parts[j];
        if PPart^.Len=0 then Break;

        NeedStyleFont:= PPart^.ColorFont<>NColorFont;
        NeedStyleBg:= PPart^.ColorBG<>AColorBG;
        NeedStyle:= NeedStyleFont or NeedStyleBg;

        StrText:= Ed.Strings.LineSub(i, PPart^.Offset+1, PPart^.Len);
        EscapeSpecChars(StrText);

        if _IsSpaces(StrText) and not NeedStyleBg then
        begin
          S+= StrText;
          Continue;
        end;

        if (PPart^.FontStyles and afsFontBold)<>0 then S+= '<b>';
        if (PPart^.FontStyles and afsFontItalic)<>0  then S+= '<i>';
        if (PPart^.FontStyles and afsFontCrossed)<>0 then S+= '<s>';

        if NeedStyle then
        begin
          DoCssStyle(
            PPart^.ColorFont, PPart^.ColorBG,
            NColorFont, AColorBG,
            StyleName, StyleText
            );
          if LStyles.IndexOf(StyleText)<0 then
            LStyles.Add(StyleText);
          S+= Format('<span class="%s">', [StyleName]);
        end;

        S:= S+StrText;
        if NeedStyle then
          S+= '</span>';

        if (PPart^.FontStyles and afsFontCrossed)<>0  then S+= '</s>';
        if (PPart^.FontStyles and afsFontItalic)<>0  then S+= '</i>';
        if (PPart^.FontStyles and afsFontBold)<>0  then S+= '</b>';
      end;
      LCode.Add(S);
    end;

    _AddPreToStrings(LCode);

    L.Add('<!-- Generated by ATSynEdit Exporter -->');
    L.Add('<html>');
    L.Add('<head>');
    L.Add('  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />');
    L.Add('  <title>'+APageTitle+'</title>');
    L.Add('  <style>');
    L.Add('    body, table {');
    L.Add('      color: '+TATHtmlColorParserA.ColorToHtmlString(NColorFont)+';');
    L.Add('      background-color: '+TATHtmlColorParserA.ColorToHtmlString(AColorBg)+';');
    L.Add('    }');
    L.Add('    pre, code {');
    L.Add('      font-family: "'+AFontName+'", sans-serif;');
    L.Add('      font-size: '+IntToStr(AFontSize)+'px;');
    L.Add('    }');
    L.Add('    table, td {');
    L.Add('      border-style: hidden;');
    L.Add('    }');
    L.Add('    td {');
    L.Add('      vertical-align: top;');
    L.Add('    }');
    L.Add('    td.num {');
    L.Add('      color: '+TATHtmlColorParserA.ColorToHtmlString(AColorNumbers)+';');
    L.Add('      text-align: right;');
    L.Add('    }');
    L.AddStrings(LStyles);
    L.Add('  </style>');
    L.Add('</head>');
    L.Add('<body>');

    if AWithNumbers then
    begin
      L.Add('<table>');
      L.Add('<tr><td class="num">');
      L.AddStrings(LNums);
      L.Add('</td>');
      L.Add('<td>');
    end;

    L.AddStrings(LCode);

    if AWithNumbers then
      L.Add('</td></tr></table>');

    L.Add('</body>');
    L.Add('</html>');

    L.SaveToFile(AFilename);
  finally
    FreeAndNil(LNums);
    FreeAndNil(LCode);
    FreeAndNil(LStyles);
    FreeAndNil(L);
  end;
end;

end.

